name: Dev Artifacts

on:
  push:
    branches:
      - master

jobs:
  build_package_job:
    runs-on: ubuntu-latest
    name: build package
    env:
      REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
      REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
      NUMBER: ${{ github.run_id }}
      ENV: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build action step for trader
        uses: ./image
        id: prometheus_client
        with:
          index-url: 'https://artifactsx.dev.grandline.link/repository/pypi-grandline/'
          repo-username: ${{ secrets.REPO_USERNAME }}
          repo-password: ${{ secrets.REPO_PASSWORD }}
          build-directory: '.'
          build-seq-id: ${{ env.NUMBER }}
